#! /bin/bash 
source /opt/ros/kinetic/setup.bash
source /home/fan/ros_slam/catkin_ws/devel/setup.bash
sudo chmod a+rw /dev/ttyS0
sudo chmod a+rw /dev/ttyS1
sudo chmod a+rw /dev/ttyS2
roslaunch gkrobot robotRunALL.launch
